services:
  main-mysql:
    image: mysql:8.0
    container_name: on-race-main-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MAIN_DB_PASSWORD}
      MYSQL_DATABASE: ${MAIN_DB_NAME}
    ports:
      - '${MAIN_DB_PORT}:3306'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - main-db-data:/var/lib/mysql

  main-redis:
    image: redis:7-alpine
    container_name: on-race-main-redis
    ports:
      - '${MAIN_REDIS_PORT}:6379'
    volumes:
      - main-redis-data:/data

volumes:
  main-db-data:
  main-redis-data:
