server:
  port: ${GATEWAY_SERVER_PORT:8080}

spring:
  application:
    name: gateway
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST:localhost}
      port: ${GATEWAY_REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - ${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:3000}
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                exposed-headers:
                  - Authorization
                  - X-Request-Id
                allow-credentials: true
                max-age: 3600
          routes:
            - id: auth-route
              uri: ${AUTH_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 50
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userOrIpKeyResolver}"
            - id: ticketing-route
              uri: ${MAIN_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/main/tickets/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userOrIpKeyResolver}"
                - name: BotDetectionFilter
                  args:
                    challengeMode: true
                    challengeUri: ${CHALLENGE_URI:http://localhost:3000/challenge}
                - name: WaitingRoomFilter
                  args:
                    queueUrl: ${WAITING_ROOM_URI:http://localhost:3000/queue}
            - id: public-route
              uri: ${MAIN_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/main/**
              filters:
                - StripPrefix=1
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 50
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userOrIpKeyResolver}"
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:43200000}
