spring:
  application:
    name: auth

  data:
    redis:
      host: ${AUTH_REDIS_HOST:localhost}
      port: ${AUTH_REDIS_PORT:6379}

  datasource:
    url: jdbc:mysql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${AUTH_JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
        format_sql: ${AUTH_HIBERNATE_FORMAT_SQL:true}
        use_sql_comments: ${AUTH_HIBERNATE_USE_SQL_COMMENTS:true}

server:
  port: ${AUTH_SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:43200000}

api:
  url:
    main: ${MAIN_SERVICE_URI}