# 서버 포트
server:
  port: 8080

spring:
  # MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/on-race?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: false

# jwt 설정
jwt:
  secret: ${jwt.secret}
  access-token-expiration: 300000
  refresh-token-expiration: 43200000

# Micrometer
management:
  tracing:
    enabled: true
    baggage:
      enabled: true
      remote-fields: traceId
      correlation:
        fields: traceId